# PART 1

### Question 1:
- values add: 20 
- It won't return an error because result is a var and it is already declared and initilized before the function. We also have num1 and num2 is passed into the function as parameters, which is accessable during the whole function. 

### Question 2:
- final result: 20 
- The code didn't return any error because result is a var, which mean that it is accessable in the function scope, since line 13 is still inside the function, result can still be used and there will be no errors at all.

### Question 3:
- values add: 20 
- It won't give any erros because result is a let variable and it can be access inside in the code block, since result is declared and initilized inside the if block and so as line 9, there is no errors generated. 

### Question 4:
- An error statement will be printed at line 13 because result is a variable that use let, which make it only accessable during the if-else statement block. Since line 13 is out of the block, result can't be use there and there will be an error for that. 

### Question 5
- It will give an error becasue you can't change result at line 7 since result is a const variable. Result is already delcared and initilized at line 5, which make the result assigned to the values 0, and it is unchangable. 

### Question 6
- It will give an error because result is a const variale and it is declared and initialized inside the if-else block and will only survive in that scope. It can't be used in line 13 because line 13 is outside of the if block. 


